workflows:
  test_satin_ios:
    name: iOS Native
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      groups:
        - surfshield_group
    integrations:
      app_store_connect: Surf Adbcloker Team
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
      email:
        recipients:
          - arthurkulik91@gmail.com
        notify:
          success: true
          failure: true
    scripts:
      - name: Set up keychain to be used for codesigning
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files com.surfshield.app --type IOS_APP_STORE --create
      - name: Set up signing certificate
        script: |
          keychain add-certificates
      - name: Set up provisioning profile
        script: |
          app-store-connect fetch-signing-files com.surfshield.app --type IOS_APP_STORE --create
      - name: Create directories
        script: |
          mkdir -p build/ios/ipa
      - name: Build app
        script: xcodebuild -project SurfShield.xcodeproj -scheme SurfShield -configuration Release archive -archivePath $CM_BUILD_DIR/build/SurfShield.xcarchive -allowProvisioningUpdates
      - name: Export IPA
        script: xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/build/SurfShield.xcarchive -exportOptionsPlist export_options.plist -exportPath $CM_BUILD_DIR/build/ios/ipa/
      - name: Show IPA files before publishing
        script: ls -la build/ios/ipa/