workflows:
  test_satin_ios:
    name: iOS Native
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      groups:
        - surfshield_group
    integrations:
      app_store_connect: Surf Adbcloker Team
    publishing:
        app_store_connect:
          auth: integration
          submit_to_testflight: true
          submit_to_app_store: false